### ISSUE TITLE
Quadro K2000 installed without modifying chassis.

### ISSUE THREAD

**Issue by BaDjinn** [bohnelang/CUDA-on-a-HP-ProLiant-DL360p-G8#3]
It's possible to install a quadro K2000, and similar sized videocards, by removing the fan shroud, leaving the bare radiator exposed to the air stream of the main chassis fans.

I've still to try my luck with a Tesla P4, but i'm pretty confident.

**Comment by bohnelang** [comment]
I guess there is not enought space for 2 slot GPU cards and there is no power plug gor the gpu card.

**Comment by BaDjinn** [comment]
The Tesla P4 requires only 75W from the PCIe slot, so in theory you can install two of them. However, I haven't had the time to check the clearances, and if I remember correctly, the second PCIe slot is an 8x slot, which could potentially hinder the performance of the second P4.

PS sorry i didn't saw your [HP-Proliant-Server-with-NVIDIA-GPU-Tesla-P4-M4-T4-CUDA](https://github.com/bohnelang/HP-Proliant-Server-with-NVIDIA-GPU-Tesla-P4-M4-T4-CUDA) repository.
