### ISSUE TITLE
im using esxi 6.7 with 1030

### ISSUE THREAD

**Issue by soru1107** [bohnelang/CUDA-on-a-HP-ProLiant-DL360p-G8#4]
i cant get anything to work in my VM running win server using a gpu... davinci resolve cant render anything
![Capture](https://github.com/bohnelang/CUDA-on-a-HP-ProLiant-DL360p-G8/assets/166170740/8d5ff8fe-858c-464d-a7ba-d5110c5adcf5)

**Comment by bohnelang** [comment]
We use bare metal Linux. Handling GPU with esxi ist difficult.

**Comment by pouriamoosavi** [comment]
Hello @soru1107. Were you able to get this working? If yes would you please explain how?
Thanks

**Comment by soru1107** [comment]
I did managed to get it to work with 1030 and a quadro 4gb i use a virtual
windows server in a esxi 6.7 and you have to find te right driver not all
will work also ib esxi settings for the virtual machine you need to select
nvidia gpu
